version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
    - method: pip
      path: auto3d

conda:
  environment: installation.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
